# 网站图标
favicon: https://cdn.jsdelivr.net/gh/Polar1sssss/FigureBed/blog/favicon.png

index_img: https://cdn.jsdelivr.net/gh/Polar1sssss/FigureBed/blog/index_img.jpg

highlight_theme: mac

subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # loop (循環打字)
  loop: true
  # source調用第三方服務
  # source: false 關閉調用
  # source: 1  調用搏天api的隨機語錄（簡體） https://api.btstu.cn/
  # source: 2  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 3  調用一句網（簡體） http://yijuzhan.com/
  # source: 4  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: false
  # 如果有英文逗號' , ',請使用轉義字元 &#44;
  # 如果有英文雙引號' " ',請使用轉義字元 &quot;
  # 開頭不允許轉義字元，如需要，請把整個句子用雙引號包住
  # 如果關閉打字效果，subtitle只會顯示sub的第一行文字
  sub: 
    - 天行健 君子以自强不息 | 地势乾 君子以厚德载物

# 头像
avatar: 
  img: https://cdn.jsdelivr.net/gh/Polar1sssss/FigureBed/blog/avatar.jpg 
  effect: false #头像会一直转圈

# 社交图标
# social:
#   fas fa-envelope: mailto:1055300264@qq.com || Email
#   fab fa-qq: 1055300264 || QQ

# 如果你有使用hexo-douban，可配置這個
douban:
   meta: true
   movies_img: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/movie.jpg
   books_img: https://cdn.jsdelivr.net/npm/blog-gallery@1.0.0/1/20200206161657.webp
#   games_img:

menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  娱乐||fas fa-list:
    图库: /gallery/ || fas fa-camera-retro 
    电影: /movies/ || fas fa-video
    书单: /books/ || fas fa-book
    游戏: /games/ || fas fa-gamepad
  留言板: /comments/ || fas fa-comments
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart card-announcement-animation

# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: true
  per_page: true

# 引入css和js
inject:
  head:
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Polar1sssss/FigureBed/css/background.css">
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Polar1sssss/FigureBed/css/macblack.css">
    #- <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/sviptzk/StaticFile_HEXO@latest/butterfly/css/pool.min.css">
    #- <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/sviptzk/StaticFile_HEXO@latest/butterfly/css/iconfont.min.css"> 
  bottom: 
    - <script src="https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@latest/Hexo/js/mouse_snow.min.js"></script>
    - <div class="aplayer no-destroy" data-id="720305850" data-server="netease" data-type="playlist" data-fixed="true" data-mini="true" data-listFolded="false" data-order="random" data-lrctype="1" data-preload="none" data-autoplay="true" muted></div>

# 文章页相关配置
post_meta: 
  page:
   date_type: both
    # created or updated or both主页文章日期是创建日或者更新日或都显示
  date_format: relative # date/relative显示日期还是相对日期
  categories: true # true or false主页是否显示分类
  tags: true # true or false主页是否显示标签
  label: true # true or false显示描述性文字
  post: 
    date_type: both # created or updated or both文章页日期是创建日或者更新日或都显示
    date_format: relative # date/relative显示日期还是相对日期
    categories: true # true or false文章页是否显示分类
    tags: true # true or false文章页是否显示标签label: true

# 文章版权
post_copyright: 
  enable: true 
  decode: false 
  license: CC BY-NC-SA 4.0 
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 打赏
reward: 
  enable: true 
  QR_code: 
    - img: https://cdn.jsdelivr.net/gh/Polar1sssss/FigureBed/blog/wechat.jpg
      link: https://cdn.jsdelivr.net/gh/Polar1sssss/FigureBed/blog/wechat.jpg
      text: 微信
    - img: https://cdn.jsdelivr.net/gh/Polar1sssss/FigureBed/blog/alipay.jpg
      link: https://cdn.jsdelivr.net/gh/Polar1sssss/FigureBed/blog/alipay.jpg
      text: 支付宝

# 相关文章
related_post: 
  enable: true
  limit: 6 #显示推荐文章数目
  date_type: created # or created or updated文章日期显示创建日或者更新日

# footer设置
footer: 
  owner: 
    enable: true 
    since: 2021

# 页脚自定义文本
custom_text:  Hi,  welcome  to  my  <a  href="https://polar1sssss.github.io/">blog</a>!

# 右下角设置-简繁切换
translate: 
  enable: true 
  #默认按钮显示文字(网站是简体，应设置为'default:繁') 
  default: 简 
  #网站默认语言，1:繁体中文, 2:简体中文
  defaultEncoding: 1 
  #延迟时间,若不在前,要设定延迟翻译时间,如100表示100ms,默认为0 
  translateDelay: 0
  #当文字是简体时，按钮显示的文字
  msgToTraditionalChinese: "繁"
  #当文字是繁体时，按钮显示的文字
  msgToSimplifiedChinese: "简"

# 右下角设置-夜间模式 
darkmode: 
  enable: true 
  # dark mode和light mode切换按钮
  button: true 
  autoChangeMode: false

# 阅读模式
readmode: true

# 卡片设置
aside: 
  enable: true 
  hide: false 
  button: true 
  mobile: true #手机页面（显示宽度< 768px ）是否显示aside内容
  position: left # left or right 
  card_author: 
    enable: true 
    description: '醉后不知天在水，满船清梦压星河'
    button: 
      enable: true 
      icon: fab fa-github
      text: Github 
      link: https://github.com/polar1sssss
  card_announcement: 
    enable: true 
    content: Welcome to Polar1sssss's Blog !
  card_recent_post: 
    enable: true 
    limit: 5
  card_tags color: true

# 访问人数统计
busuanzi: 
  site_uv: true 
  site_pv: true 
  page_pv: true

# 评论
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use:
    - Valine
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page

valine:
  appId: DwF80OVECXpyRq6sKDek9PWG-MdYXbMMI
  appKey: GTchasgn59DhpvvR4CciOTVH
  pageSize: 10 # comment list page size
  avatar: monsterid # gravatar style https://valine.js.org/#/avatar
  lang: zh-CN
  placeholder: 记得留下你的昵称和邮箱...可以快速收到回复 # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail #valine comment header info (nick/mail/link)
  recordIP: false # Record reviewer IP
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  bg: /img/comment_bg.png # valine background
  emojiCDN: # emoji CDN
  enableQQ: false # enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  requiredFields: nick,mail # required fields (nick/mail)
  visitor: false
  option: